### PR TITLE
Incorporate Thomas Pornin's suggestions. 

### PR DESCRIPTION
**Pull request by isislovecruft**
This PR consists of several proposed changes to address suggestions brought up by Thomas Pornin [here](https://mailarchive.ietf.org/arch/msg/crypto-panel/isgCxg9ddxoPkNnOdGbwK2Z2_Cw/).

### CODE REVIEW

**Comment by isislovecruft** [comment]
Some comments and open questions:

1. Thomas brings up the rather permissible language around the canonicalisation of scalars in our draft:
   > page 12: the provisions on canonical encodings of scalars use "SHOULD";
   > maybe that should be "MUST", for the same reasons that make canonical
   > encodings of group elements desirable? Otherwise, you end up with
   > things like malleable signatures, and Bitcoin is sad.

   While I understand that we've done this for maximum backwards compatibility with existing implementations of curve25519/ed25519, strict canonicalisation of scalars might in fact be an API feature we should require.

2. Another fair point is that, iff we are requiring 64 uniformly random bytes as input our hash-to-group procedure, in order to perform the reduction twice and add the two elements together, should we be requiring 128 bytes for ed448/decaf?
   > page 17: reducing an integer modulo l: as on page 12, there should be a
   > word about what is the point here. Also, one may note that a 512-bit
   > integer is not very much larger than the 446-bit subgroup order; but it
   > is still fine here because l is very close to a power of 2. This might
   > be worth a comment (otherwise, one might imagine that the paragraph was
   > copy&pasted from the one in section 4.4, and that the "64" is a typo).

3.  I actually do not remember why the negative square root was used here, and my inclination is to believe it was an artefact of Mike's original work on Decaf.
    > page 7: non-zero quadratic residues have two distinct square roots, exactly
    > one of them being non-negative (in the sense defined in section 2.1). The
    > constants SQRT_M1 = sqrt(-1) and INVSQRT_A_MINUS_D = 1/sqrt(A-D) both
    > use the non-negative square root, but SQRT_AD_MINUS_ONE = sqrt(A*D - 1)
    > uses the negative square root. Is there a specific reason for this choice?
    > (If a rationale is added, it would be nice to say that A = -1; this allows
    > verification of the values.)
    > (Also, it would be nice to add somewhere that the formulas leverage
    > the fact that A = -1 in several places and cannot be applied "as is"
    > on other Edwards curves where A != -1.)

4. So this one I can concede assuredly is an artefact of Mike's Decaf sage code, which to my memory we kept as we found it charming (pun intended).
   > page 10: is there a traditional reason why the denominator is called
   > "enchanted"? This is maths, not magic (despite superficial similarities,
   > these are distinct activities).

**Comment by isislovecruft** [comment]
This is done except for potential changes regarding the discussion points above.

**Comment by hdevalence** [comment]
> Some comments and open questions:
> 
>     1. Thomas brings up the rather permissible language around the canonicalisation of scalars in our draft:
>        > page 12: the provisions on canonical encodings of scalars use "SHOULD";
>        > maybe that should be "MUST", for the same reasons that make canonical
>        > encodings of group elements desirable? Otherwise, you end up with
>        > things like malleable signatures, and Bitcoin is sad.
>        
>        
>        While I understand that we've done this for maximum backwards compatibility with existing implementations of curve25519/ed25519, strict canonicalisation of scalars might in fact be an API feature we should require.

Yes, the reason was to allow a ristretto255 implementation based on Ed25519 to use the same scalar type as the Ed25519 library.  The language could be changed to MUST, but then most existing implementations wouldn't be conformant with it. So I think this ultimately hinges on whether it's better to have a spec with MUST that most implementations are out of compliance with, or a spec with SHOULD that most implementations would be in compliance with.  Either way is fine with me.

>     2. Another fair point is that, iff we are requiring 64 uniformly random bytes as input our hash-to-group procedure, in order to perform the reduction twice and add the two elements together, should we be requiring 128 bytes for ed448/decaf?
>        > page 17: reducing an integer modulo l: as on page 12, there should be a
>        > word about what is the point here. Also, one may note that a 512-bit
>        > integer is not very much larger than the 446-bit subgroup order; but it
>        > is still fine here because l is very close to a power of 2. This might
>        > be worth a comment (otherwise, one might imagine that the paragraph was
>        > copy&pasted from the one in section 4.4, and that the "64" is a typo).

I'm not sure I follow, the comment about page 17 (and the prior one it references about page 12) seem to be about scalar reductions and how many excess bits are required to obtain uniform output after reduction, not about the map-and-add procedure in the hash-to-group map.

We should clarify that the choice of a 512-bit starting value is motivated by compatibility with Ed25519, not for security reasons; as Thomas notes, it's overkill from a security point of view. 

>     3. I actually do not remember why the negative square root was used here, and my inclination is to believe it was an artefact of Mike's original work on Decaf.
>        > page 7: non-zero quadratic residues have two distinct square roots, exactly
>        > one of them being non-negative (in the sense defined in section 2.1). The
>        > constants SQRT_M1 = sqrt(-1) and INVSQRT_A_MINUS_D = 1/sqrt(A-D) both
>        > use the non-negative square root, but SQRT_AD_MINUS_ONE = sqrt(A*D - 1)
>        > uses the negative square root. Is there a specific reason for this choice?
>        > (If a rationale is added, it would be nice to say that A = -1; this allows
>        > verification of the values.)
>        > (Also, it would be nice to add somewhere that the formulas leverage
>        > the fact that A = -1 in several places and cannot be applied "as is"
>        > on other Edwards curves where A != -1.)

No, the reason that SQRT_AD_MINUS_ONE has a "negative" square root is because I computed its value in Sage, and Sage chooses the value with the least absolute residue by default.  If Ed25519 used the Ed448-style definition of negativity (least absolute residue / high bit), this would be the nonnegative one, but instead it uses the low bit.  The choice doesn't matter, but it can't be changed now without changing the hash-to-group map.
 
>     4. So this one I can concede assuredly is an artefact of Mike's Decaf sage code, which to my memory we kept as we found it charming (pun intended).
>        > page 10: is there a traditional reason why the denominator is called
>        > "enchanted"? This is maths, not magic (despite superficial similarities,
>        > these are distinct activities).

The naming is related to Mike's [ingenious trick](https://ristretto.group/details/encoding_in_extended.html#batching-the-inversion-and-inverse-square-root) for computing the encoding in the cofactor-8 case with only a single inverse square root.  Clever use of the curve equation gives a number that relates two of the quantities, called `magic` in Mike's script. I named the variable `enchanted_denominator` to reflect the fact that it had magic multiplied in. I'm also partial to the naming, so I'd prefer to keep it.

**Comment by chris-wood** [comment]
@hdevalence chiming in, in case it's helpful:

- I'd keep a SHOULD for the scalar encoding issue and clarify that this was done for backwards compatibility. 
- Do we know what the bias is if reducing a decaf448 scalar mod `l`? And how does this bias compare to the reduction for ristretto255? If they're both negligible, which I think is the case, maybe we just add a comment to that effect, as Thomas suggests? For example, `Reducing mod l ensures the resulting scalar is uniformly distributed across the subgroup since l is close to a power of 2.` 🤷

**Comment by chris-wood** [comment]
Bump?

**Comment by bitwiseshiftleft** [comment]
Huh, somehow I don't have an email record of this thread... maybe it got junked somehow.

We can toggle the sign of SQRT_AD_MINUS_ONE since it's only used once, multiplied by `N = c * (r - 1) * D_MINUS_ONE_SQ - v`.  We can just switch n to be `v - c * (r - 1) * D_MINUS_ONE_SQ`.

I agree that "enchanted" should probably be changed to sound less magical.  We can just call it den3.

The total variation distance (TVD, aka "statistical difference") in reducing a random value mod `N` to one mod `m` is at most `(N mod m) / N`.  So for Ed25519 and Ed448 this is on the order of `2^-262.15` and `2^-222.96` respectively, which are negligible and both less than or on the order of the curve's security.  Interestingly, going from 448 to 512 doesn't meaningfully help ed448 in terms of TVD, though it does help in other measures like L2 norm.

**Comment by hdevalence** [comment]
@bitwiseshiftleft 

> We can toggle the sign of SQRT_AD_MINUS_ONE since it's only used once, multiplied by `N = c * (r - 1) * D_MINUS_ONE_SQ - v`. We can just switch n to be `v - c * (r - 1) * D_MINUS_ONE_SQ`.

Hmm, if the formulas are changed to toggle the sign and the constant without affecting the wire format, is there a possibility of confusion for someone who looks at an existing implementation's formulas and constants as a reference? Is that worth having a nonnegative constant value?

**Comment by isislovecruft** [comment]
> >    Some comments and open questions:
> >
> >    1. Thomas brings up the rather permissible language around the canonicalisation of scalars in our draft:
> >       > page 12: the provisions on canonical encodings of scalars use "SHOULD";
> >       > maybe that should be "MUST", for the same reasons that make canonical
> >       > encodings of group elements desirable? Otherwise, you end up with
> >       > things like malleable signatures, and Bitcoin is sad.
> >       
> >       
> >    While I understand that we've done this for maximum backwards compatibility with existing implementations of curve25519/ed25519, strict canonicalisation of scalars might in fact be an API feature we should require.
> >
> Yes, the reason was to allow a ristretto255 implementation based on Ed25519 to use the same scalar type as the Ed25519 library. The language could be changed to MUST, but then most existing implementations wouldn't be conformant with it. So I think this ultimately hinges on whether it's better to have a spec with MUST that most implementations are out of compliance with, or a spec with SHOULD that most implementations would be in compliance with. Either way is fine with me.

Going with keeping "SHOULD", and I'll add a note that we strongly recommend doing so, and mention the desire for wanting to allow implementations to make use of existing ed25519 arithmetic. This is reflected in [a07aa98](https://github.com/cfrg/draft-irtf-cfrg-ristretto255/pull/9/commits/a07aa98bcb18246f60fb79a1b428711d99ec8ee4).

**Comment by isislovecruft** [comment]
Added another note on backwards compatibility for potentially non-canonicalised scalars in previously existing ed448 implementations in [def91bc](https://github.com/cfrg/draft-irtf-cfrg-ristretto255/pull/9/commits/def91bcfde4428472a7a463ebe1a020ebed2d8dc). (@bitwiseshiftleft I'm not sure how many ed448 implementations allow this?)

**Comment by isislovecruft** [comment]
> >    3. I actually do not remember why the negative square root was used here, and my inclination is to believe it was an artefact of Mike's original work on Decaf.
> >       > page 7: non-zero quadratic residues have two distinct square roots, exactly
> >       > one of them being non-negative (in the sense defined in section 2.1). The
> >       > constants SQRT_M1 = sqrt(-1) and INVSQRT_A_MINUS_D = 1/sqrt(A-D) both
> >       > use the non-negative square root, but SQRT_AD_MINUS_ONE = sqrt(A*D - 1)
> >       > uses the negative square root. Is there a specific reason for this choice?
> >       > (If a rationale is added, it would be nice to say that A = -1; this allows
> >       > verification of the values.)
> >       > (Also, it would be nice to add somewhere that the formulas leverage
> >       > the fact that A = -1 in several places and cannot be applied "as is"
> >       > on other Edwards curves where A != -1.)
>
> No, the reason that SQRT_AD_MINUS_ONE has a "negative" square root is because I computed its value in Sage, and Sage chooses the value with the least absolute residue by default. If Ed25519 used the Ed448-style definition of negativity (least absolute residue / high bit), this would be the nonnegative one, but instead it uses the low bit. The choice doesn't matter, but it can't be changed now without changing the hash-to-group map.

Added A=-1 and clarification of rationale for negative square root in [cad98d3](https://github.com/cfrg/draft-irtf-cfrg-ristretto255/pull/9/commits/cad98d335604969cf1b17f8717392de1bdda586c).

**Comment by isislovecruft** [comment]
It sounds like we're all in agreement that we continue to name things infused with magic accordingly, so I'm keeping the enchanted denominator variable. I think this PR is ready to be merged. Hopefully I've sufficiently addressed Thomas's comments (also thank you for the feedback!).

**Pull request merged**
